// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamData.Models
{
    public partial class Accounts
    {
        public int EmailId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime CreationDate { get; set; }
        public int CountryId { get; set; }
        public int UserId { get; set; }

        public virtual Countries Country { get; set; }
        public virtual Users User { get; set; }
    }
}