// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamData.Models
{
    public partial class Countries
    {
        public Countries()
        {
            Accounts = new HashSet<Accounts>();
            Devs = new HashSet<Devs>();
            Servers = new HashSet<Servers>();
            CompaniesCompany = new HashSet<Companies>();
        }

        public int CountryId { get; set; }
        public string CountryName { get; set; }

        public virtual ICollection<Accounts> Accounts { get; set; }
        public virtual ICollection<Devs> Devs { get; set; }
        public virtual ICollection<Servers> Servers { get; set; }

        public virtual ICollection<Companies> CompaniesCompany { get; set; }
    }
}