// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamData.Models
{
    public partial class Devs
    {
        public Devs()
        {
            GamesGame = new HashSet<Games>();
        }

        public int DevId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CountryId { get; set; }
        public int CompanyId { get; set; }

        public virtual Companies Company { get; set; }
        public virtual Countries Country { get; set; }

        public virtual ICollection<Games> GamesGame { get; set; }
    }
}