// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamData.Models
{
    public partial class Games
    {
        public Games()
        {
            Servers = new HashSet<Servers>();
            DevelopersDev = new HashSet<Devs>();
            UsersUser = new HashSet<Users>();
        }

        public int GameId { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public int CompanyId { get; set; }

        public virtual Companies Company { get; set; }
        public virtual ICollection<Servers> Servers { get; set; }

        public virtual ICollection<Devs> DevelopersDev { get; set; }
        public virtual ICollection<Users> UsersUser { get; set; }
    }
}