// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamData.Models
{
    public partial class Servers
    {
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public int? GameId { get; set; }
        public int CompanyId { get; set; }
        public int CountryId { get; set; }

        public virtual Companies Company { get; set; }
        public virtual Countries Country { get; set; }
        public virtual Games Game { get; set; }
    }
}