// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamData.Models
{
    public partial class Users
    {
        public Users()
        {
            GamesGame = new HashSet<Games>();
        }

        public int UserId { get; set; }
        public string Nickname { get; set; }

        public virtual Accounts Accounts { get; set; }

        public virtual ICollection<Games> GamesGame { get; set; }
    }
}